spring:
#  resources:
#    static-locations: classpath:/static/dist/,classpath:/static/lewan/
  profiles:
      active: dev
#  freemarker:
#    template-loader-path: classpath:/static/dist/,classpath:/static/lewan/
#    suffix: .html
#    content-type: text/html
#    charset: UTF-8
  redis:
      host: localhost
      password:
      port: 6379
  servlet:
      multipart:
        max-request-size: 500MB
        max-file-size: 500MB
server:
  port: 8089
  error:
    whitelabel:
      enabled: true
  tomcat:
    basedir: F:\temp\
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: top.cfl.cflwork.pojo
  configuration:
    cache-enabled: false
    lazy-loading-enabled: true
    default-statement-timeout: 20000
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
     top.cflwork.dao: debug
snowflake:
  workerId: 2 #同一个服务之间集群时可以一样，不同服务必须不同
  datacenterId: 1 #不同的数据中心不一样
cflwork:
  auth:
    ignores:
    - /*/ignore/**
    - /admin/clearCache
    - /dd/**
    - /nation/**
    - /region/**
    - /sysPerm/findAdminTreeMenu
    - /standard/**
    - /upload/**
    - /iconfont/getIconfontLink
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7